YMAGINE_JNI:=$(call my-dir)

YMAGINE_BUILD_ANDROID:=false
YMAGINE_BUILD_SHARED:=false

ifeq ($(BUILD_ANDROID),true)
YMAGINE_BUILD_ANDROID:=true
ifneq ($(NDK_ROOT),)
YMAGINE_BUILD_SHARED:=true
endif
endif

ifeq ($(BUILD_HOST),true)
YMAGINE_BUILD_ANDROID:=false
YMAGINE_BUILD_SHARED:=true
endif

# Core features
YMAGINE_CONFIG_BITMAP:=true
YMAGINE_CONFIG_BITMAP_JPEG:=true
YMAGINE_CONFIG_BITMAP_WEBP:=true
YMAGINE_CONFIG_BITMAP_PNG:=true
YMAGINE_CONFIG_BITMAP_GIF:=false
YMAGINE_CONFIG_XMP:=true
YMAGINE_CONFIG_CLASSIFIER:=false
YMAGINE_CONFIG_VISION:=false
YMAGINE_CONFIG_VIDEO:=false
YMAGINE_CONFIG_DLIB:=false
ifeq (,$(wildcard $(YMAGINE_JNI)/../plugins/vision))
YMAGINE_CONFIG_CLASSIFIER:=false
endif
ifeq (,$(wildcard $(YMAGINE_JNI)/../plugins/video))
YMAGINE_CONFIG_VIDEO:=false
endif

ifeq ($(BUILD_JAVASCRIPT),true)
#YMAGINE_CONFIG_CLASSIFIER:=false
#YMAGINE_CONFIG_VIDEO:=false
endif

# Code layout
YMAGINE_PLUGINS_ROOT:=$(YMAGINE_ROOT)/plugins
YMAGINE_3RDPARTIES:=$(YMAGINE_ROOT)/../../external

# Local mirrors of 3rd parties modules
ZLIB_ROOT:=$(YMAGINE_3RDPARTIES)/zlib
LZF_ROOT:=$(YMAGINE_3RDPARTIES)/liblzf
JPEGTURBO_ROOT:=$(YMAGINE_3RDPARTIES)/jpeg-turbo
WEBP_ROOT:=$(YMAGINE_3RDPARTIES)/webp
PNG_ROOT:=$(YMAGINE_3RDPARTIES)/libpng
CCV_ROOT:=$(YMAGINE_3RDPARTIES)/ccv

# Core layout
YOSAL_ROOT:=$(YMAGINE_ROOT)/../yosal
