YMAGINE_JNI:=$(call my-dir)

YMAGINE_BUILD_ANDROID:=false
YMAGINE_BUILD_SHARED:=false

ifeq ($(BUILD_ANDROID),true)
YMAGINE_BUILD_ANDROID:=true
ifneq ($(NDK_ROOT),)
YMAGINE_BUILD_SHARED:=true
endif
endif

ifeq ($(BUILD_HOST),true)
YMAGINE_BUILD_ANDROID:=false
YMAGINE_BUILD_SHARED:=true
endif

# Core features
YMAGINE_CONFIG_BITMAP:=true
YMAGINE_CONFIG_BITMAP_JPEG:=true
YMAGINE_CONFIG_BITMAP_WEBP:=true
YMAGINE_CONFIG_XMP:=true
YMAGINE_CONFIG_CLASSIFIER:=false
YMAGINE_CONFIG_VPX:=false

# Code layout
YMAGINE_PLUGINS_ROOT:=$(YMAGINE_ROOT)/plugins
YMAGINE_3RDPARTIES:=$(YMAGINE_ROOT)/../../external

# Local mirrors of 3rd parties modules
LZF_ROOT:=$(YMAGINE_3RDPARTIES)/liblzf
JPEGTURBO_ROOT:=$(YMAGINE_3RDPARTIES)/jpeg-turbo
WEBP_ROOT:=$(YMAGINE_3RDPARTIES)/webp
CCV_ROOT:=$(YMAGINE_3RDPARTIES)/ccv

# Core layout
YOSAL_ROOT:=$(YMAGINE_ROOT)/../yosal
